-- ============================================================================
-- TradeWizard Automated Market Monitor - Initial Schema Migration
-- ============================================================================
-- Creates all required tables for the Automated Market Monitor
-- ============================================================================

-- ============================================================================
-- Markets Table
-- ============================================================================
-- Stores information about prediction markets being monitored
CREATE TABLE IF NOT EXISTS markets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  condition_id TEXT UNIQUE NOT NULL,
  question TEXT NOT NULL,
  description TEXT,
  event_type TEXT NOT NULL,
  market_probability DECIMAL(5,4),
  volume_24h DECIMAL(20,2),
  liquidity DECIMAL(20,2),
  status TEXT NOT NULL DEFAULT 'active', -- active, inactive, resolved
  resolved_outcome TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_analyzed_at TIMESTAMP WITH TIME ZONE,
  trending_score DECIMAL(10,4)
);

-- Indexes for markets table
CREATE INDEX IF NOT EXISTS idx_markets_status ON markets(status);
CREATE INDEX IF NOT EXISTS idx_markets_last_analyzed ON markets(last_analyzed_at);
CREATE INDEX IF NOT EXISTS idx_markets_trending_score ON markets(trending_score DESC);
CREATE INDEX IF NOT EXISTS idx_markets_condition_id ON markets(condition_id);

-- ============================================================================
-- Recommendations Table
-- ============================================================================
-- Stores trade recommendations generated by the Market Intelligence Engine
CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  market_id UUID REFERENCES markets(id) ON DELETE CASCADE,
  direction TEXT NOT NULL, -- LONG_YES, LONG_NO, NO_TRADE
  fair_probability DECIMAL(5,4),
  market_edge DECIMAL(5,4),
  expected_value DECIMAL(10,4),
  confidence TEXT NOT NULL, -- high, moderate, low
  entry_zone_min DECIMAL(5,4),
  entry_zone_max DECIMAL(5,4),
  target_zone_min DECIMAL(5,4),
  target_zone_max DECIMAL(5,4),
  explanation TEXT,
  catalysts JSONB,
  risks JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for recommendations table
CREATE INDEX IF NOT EXISTS idx_recommendations_market_id ON recommendations(market_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_created_at ON recommendations(created_at DESC);

-- ============================================================================
-- Agent Signals Table
-- ============================================================================
-- Stores individual agent signals that contribute to recommendations
CREATE TABLE IF NOT EXISTS agent_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  market_id UUID REFERENCES markets(id) ON DELETE CASCADE,
  recommendation_id UUID REFERENCES recommendations(id) ON DELETE CASCADE,
  agent_name TEXT NOT NULL,
  agent_type TEXT NOT NULL,
  fair_probability DECIMAL(5,4),
  confidence DECIMAL(3,2),
  direction TEXT NOT NULL,
  key_drivers JSONB,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for agent_signals table
CREATE INDEX IF NOT EXISTS idx_agent_signals_market_id ON agent_signals(market_id);
CREATE INDEX IF NOT EXISTS idx_agent_signals_recommendation_id ON agent_signals(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_agent_signals_agent_name ON agent_signals(agent_name);

-- ============================================================================
-- Analysis History Table
-- ============================================================================
-- Tracks the history of market analyses for monitoring and debugging
CREATE TABLE IF NOT EXISTS analysis_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  market_id UUID REFERENCES markets(id) ON DELETE CASCADE,
  analysis_type TEXT NOT NULL, -- initial, update, manual
  status TEXT NOT NULL, -- success, failed, partial
  duration_ms INTEGER,
  cost_usd DECIMAL(10,4),
  agents_used JSONB,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for analysis_history table
CREATE INDEX IF NOT EXISTS idx_analysis_history_market_id ON analysis_history(market_id);
CREATE INDEX IF NOT EXISTS idx_analysis_history_created_at ON analysis_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_history_status ON analysis_history(status);

-- ============================================================================
-- LangGraph Checkpoints Table
-- ============================================================================
-- Stores LangGraph workflow checkpoints for state persistence and recovery
CREATE TABLE IF NOT EXISTS langgraph_checkpoints (
  thread_id TEXT NOT NULL,
  checkpoint_id TEXT NOT NULL,
  parent_checkpoint_id TEXT,
  checkpoint JSONB NOT NULL,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (thread_id, checkpoint_id)
);

-- Indexes for langgraph_checkpoints table
CREATE INDEX IF NOT EXISTS idx_langgraph_checkpoints_thread_id ON langgraph_checkpoints(thread_id);
CREATE INDEX IF NOT EXISTS idx_langgraph_checkpoints_created_at ON langgraph_checkpoints(created_at DESC);

-- ============================================================================
-- Updated At Trigger Function
-- ============================================================================
-- Automatically update the updated_at timestamp when a row is modified
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to markets table
DROP TRIGGER IF EXISTS update_markets_updated_at ON markets;
CREATE TRIGGER update_markets_updated_at
  BEFORE UPDATE ON markets
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Apply updated_at trigger to recommendations table
DROP TRIGGER IF EXISTS update_recommendations_updated_at ON recommendations;
CREATE TRIGGER update_recommendations_updated_at
  BEFORE UPDATE ON recommendations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
